[package]
name = "standup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1"
config_crate = { version = "0.13.2", package = "config" }